# Copyright (C) 2024-2025  The Software Heritage developers
# See the AUTHORS file at the top-level directory of this distribution
# License: GNU Affero General Public License version 3, or any later version
# See top-level LICENSE file for more information

# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentOriginMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sha1_git', models.CharField(db_index=True, help_text='SHA1 Git hash of the content object', max_length=40)),
                ('origin_url', models.CharField(help_text='Origin URL where this content was saved from', max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this mapping was created')),
            ],
            options={
                'db_table': 'content_origin_mapping',
                'indexes': [
                    models.Index(fields=['content_sha1_git'], name='content_origin_mapping_content_sha1_git_idx'),
                    models.Index(fields=['origin_url'], name='content_origin_mapping_origin_url_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=['content_sha1_git', 'origin_url'], name='unique_content_origin_mapping'),
                ],
            },
        ),
    ]
